### ISSUE TITLE
NordVPN antivirus flags the zip release as a virus

### ISSUE THREAD

**Issue by technoalli3** [ZenithVal/OSCLeash#15]
![image](https://user-images.githubusercontent.com/92867135/229233998-d4864ade-8461-4ca1-a9ea-64120a9d7514.png)
As shown above, it thinks that it's a virus. It is listed as a HEUR/APC threat
![image](https://user-images.githubusercontent.com/92867135/229234118-acab9449-f46b-4e34-b6c2-921ab2df5b81.png)

**Comment by ZenithVal** [comment]
False positive. 
You can view the source code here on github and build it yourself if you want.

**Comment by CuteWaterBeary** [comment]
![2023-04-13-20-09-13](https://user-images.githubusercontent.com/103973703/231931972-68db3766-590b-4adf-9f73-aac9d5d19f83.png)
![2023-04-13-20-08-18](https://user-images.githubusercontent.com/103973703/231931980-3a20cbbd-4c2e-4c68-bad7-7af37558d55e.png)



https://www.virustotal.com/gui/file/69fb1905c9c2452ee63021e4615a044ee4bf83e3d29c1b919b252a688d91784a

https://www.virustotal.com/gui/file/3870c734a4cb65e32b69a4dff8da2f5c0dc8aa0c346dc107fa1ea752d73e2434/detection

**Comment by ZenithVal** [comment]
Refer to previous comment.
