### ISSUE TITLE
Potential fix for arm locking bug

### ISSUE THREAD

**Issue by ShaunDreclin** [ZenithVal/OSCLeash#18]
I just saw this vrchat canny post: https://feedback.vrchat.com/feature-requests/p/osc-locks-arms

The user McArdellje came up with this solution to prevent your arms locking to your sides when getting dragged around on a leash:

> This specifically only occurs when using any "/input/" OSC parameters and, while still a bug, can be worked around by setting the parameter's value to 0 at least once per second.
I found that trying to send it once per second was not stable enough though I found that sending a value of 0 every 0.4 seconds and waiting 0.01 seconds before sending the correct value again entirely prevented this bug while adding minimal "jitter" to movements

Edit: Whoops, just saw that you already commented about this on another github issue 😅

Could this fix be implemented into OSCLeash? Would be a huge quality of life improvement

**Comment by ZenithVal** [comment]
Nullstalgia's rewrite has this. https://github.com/nullstalgia/OSCLeash
I've not replicated it as imo, the controller emulator is a better workaround for that bug atm.

**Comment by ZenithVal** [comment]
As of the most recent VRC Open beta, this issue is fixed.
https://docs.vrchat.com/docs/vrchat-202411
