### ISSUE TITLE
2.1.2 causes an error on install, fresh or update

### ISSUE THREAD

**Issue by noideaman** [ZenithVal/OSCLeash#23]
![image](https://github.com/ZenithVal/OSCLeash/assets/39884745/3fabc6ed-93dc-43b3-9218-aed83ad5559d)
i think this shortcut link is causing issues as the name matches the error in the msi
https://github.com/ZenithVal/OSCLeash/blob/69e6f46a2c629461105abbe0e0db36816affff96/Build/BuildInstaller.py#L22

**Comment by noideaman** [comment]
Yep just built it on my dev box with the ..\ removed from the shortcut name, working good now

**Comment by ZenithVal** [comment]
Fixed in v2.1.3
