### ISSUE TITLE
When I add the leash the physbones go crazy

### ISSUE THREAD

**Issue by MonkeyNBananas** [ZenithVal/OSCLeash#28]
When I add the leash the physbones go crazy, and it won't connect to the app, or provide movement

**Comment by ZenithVal** [comment]
This is an avatar setup issue~ it sounds like you've put the OSCLeash physbone on something that already has a physbone but I can't know for sure.

**Comment by ZenithVal** [comment]
Going to assume this is solved. If you need avatar related help, please reach out in the discord~ it's easier to solve with real time chat.
