### ISSUE TITLE
v2.2.0 Missing Position Constraint

### ISSUE THREAD

**Issue by Garen7** [ZenithVal/OSCLeash#32]
The compass says missing script where there should be a position constraint. This affects both the prefab and modular avatar unitypackage file in releases. Using an older version will have the position constraint component still there

![image](https://github.com/user-attachments/assets/226312eb-6990-416a-8d86-864522da5099)

**Comment by ZenithVal** [comment]
Your VRC SDK appears to be out of date. OSCLeash uses VRC constraints as of v2.2.0.
