### ISSUE TITLE
I'm unable to get it to work

### ISSUE THREAD

**Issue by ShayBox** [ZenithVal/OSCLeash#9]
The script doesn't appear to be receiving any data from VRChat, the console output never changes.  
It sends default data on startup to VRChat and appears in the Debug menu, maybe it's a prefab setup issue, the instructions aren't very clear.  
Eventually I'd like to implement the functionality ~~into my Rust program and~~ on all my public avatars.  
You should try getting this functionality put into https://github.com/VolcanicArts/VRCOSC

**Comment by GeekAndProud** [comment]
I have created a GUI version of this app, not tested yet as its impossible to grab stuff in desktop
[https://github.com/GeekAndProud/OSCLeashGUI](url)
[https://i.imgur.com/nDN6QEz.png](url)

**Comment by GeekAndProud** [comment]
I have created a GUI version of this app, not tested yet as its impossible to grab stuff in desktop
[https://github.com/GeekAndProud/OSCLeashGUI](url)
[https://i.imgur.com/nDN6QEz.png](https://i.imgur.com/nDN6QEz.png)

**Comment by ShayBox** [comment]
This could probably be made easier to setup with VRCFury
